name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anaconda-anon-usage=0.5.0
  - appnope=0.1.4
  - archspec=0.2.3
  - asttokens=3.0.0
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - conda=25.3.1
  - conda-anaconda-telemetry=0.1.1
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.9.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.11.0
  - cryptography=43.0.3
  - dataclasses=0.8
  - debugpy=1.8.11
  - decorator=5.2.1
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fmt=9.1.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libarchive=3.7.4
  - libcurl=8.9.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.4
  - libiconv=1.16
  - libmamba=1.5.11
  - libmambapy=1.5.11
  - libnghttp2=1.57.0
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.5.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.2.13
  - lxml=5.2.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - menuinst=2.2.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openjpeg=2.5.0
  - openssl=3.4.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.19.1
  - pypdf2=3.0.1
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0.post0
  - python-docx=1.1.2
  - python-pptx=1.0.2
  - python.app=3
  - python_abi=3.12
  - pyzmq=25.1.1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xlsxwriter=3.2.2
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asyncer==0.0.7
      - asyncpg==0.30.0
      - attrs==25.1.0
      - beautifulsoup4==4.13.3
      - bidict==0.23.1
      - bleach==6.2.0
      - blinker==1.9.0
      - boto3==1.37.14
      - botocore==1.37.14
      - cachetools==5.5.2
      - chainlit==2.4.1
      - chevron==0.14.0
      - clarabel==0.10.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - contourpy==1.3.1
      - cvxpy==1.6.4
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - et-xmlfile==2.0.0
      - farama-notifications==0.0.4
      - fastapi==0.115.11
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - filetype==1.2.0
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.69.1
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - importlib-metadata==6.11.0
      - jinja2==3.1.5
      - jiter==0.9.0
      - jmespath==1.0.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - langchain==0.3.21
      - langchain-community==0.3.20
      - langchain-core==0.3.45
      - langchain-deepseek==0.1.2
      - langchain-experimental==0.3.4
      - langchain-openai==0.3.9
      - langchain-text-splitters==0.3.7
      - langsmith==0.3.15
      - lazify==0.4.0
      - literalai==0.1.103
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.0
      - mcp==1.3.0
      - mdurl==0.1.2
      - minigrid==2.5.0
      - mistune==3.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.30.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - numpy==1.26.4
      - openai==1.66.3
      - openpyxl==3.1.5
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-exporter-otlp-proto-http==1.29.0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - orjson==3.10.15
      - osqp==0.6.7.post3
      - p2j==1.3.2
      - packaging==23.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - pillow==10.4.0
      - ply==3.11
      - propcache==0.3.0
      - protobuf==5.29.3
      - pulp==3.0.2
      - pyarrow==19.0.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pydeck==0.9.1
      - pygame==2.6.1
      - pyjwt==2.10.1
      - pyomo==6.9.1
      - pyparsing==3.2.1
      - python-dotenv==1.0.0
      - python-engineio==4.11.2
      - python-multipart==0.0.18
      - python-socketio==5.12.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - s3transfer==0.11.4
      - scipy==1.15.2
      - scs==3.2.7.post2
      - simple-websocket==1.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.39
      - sse-starlette==2.2.1
      - stable-baselines3==2.5.0
      - starlette==0.41.3
      - streamlit==1.29.0
      - sympy==1.13.1
      - syncer==2.0.3
      - tabulate==0.9.0
      - tenacity==8.5.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.6.0
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - tzlocal==5.3.1
      - uptrace==1.29.0
      - uvicorn==0.34.0
      - validators==0.34.0
      - watchfiles==0.20.0
      - webencodings==0.5.1
      - wrapt==1.17.2
      - wsproto==1.2.0
      - yarl==1.18.3
